CLIENT:
  HOST: '192.168.0.8'
  PORT: 8082
  MACHINE_NAME: 'test'
  TIMEOUT: 10

SENSOR:
  RATE: 30
  READ_TIMEOUT: 10
  DEVICES:
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNEL: 'ai0'
    CHANNEL_NAMES: ['cDAQ1Mod1_ai0']

FILE:
  DIRECTORY: 'data'
  EXTERNAL_DIRECTORY: 'data'

MODEL:
  SEQ_LEN: 3
  LATENT_DIM: 64
  LEARNING_RATE: 0.001
  EPOCH: 1
  BATCH_SIZE: 50