CLIENT:
  HOST: 'localhost'
  PORT: 8082
  MACHINE_NAME: 'test'
  TIMEOUT: 10

SENSOR:
  RATE: 30
  READ_TIMEOUT: 10
  DEVICES:
  - NAME: 'temp'
    TYPE: 'TEMP'
    CHANNEL: 'ai0'
    CHANNEL_NAMES: ['temp_ai0']
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNEL: 'ai0:1'
    CHANNEL_NAMES: ['vib_ai0', 'vib_ai1']

FILE:
  DIRECTORY: 'data'
  EXTERNAL_DIRECTORY: 'data'

MODEL:
  SEQ_LEN: 30
  LATENT_DIM: 64
  TEST_SIZE: 0.001
  LEARNING_RATE: 0.001