DAQ:
  RATE: 30
  DEVICES:
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNELS: ['ai0', 'ai1', 'ai2']
    CHANNEL_NAMES: ['pump1_vib', 'pump2_vib', 'm2_vib2_right']
  - NAME: 'vib2'
    TYPE: 'VIB'
    CHANNELS: ['ai0', 'ai1']
    CHANNEL_NAMES: ['coating_vib1', 'coating_vib2']
#  - NAME: 'temp'
#    TYPE: 'TEMP'
#    CHANNELS: ['ai0']
#    CHANNEL_NAMES: ['m1_temp']


MACHINE:
- NAME: 'VacuumPump1'
  CHANNEL_NAMES: ['pump1_vib']
  DATA_SEND_MODE: True
  FAULT_DETECT_MODE: False
  HOST: '192.168.0.8'
  PORT: 8082
  TIMEOUT: 60
  FAULT_DETECT_MODEL: ''
  THRESHOLD: 500

- NAME: 'VacuumPump2'
  CHANNEL_NAMES: ['pump2_vib']
  DATA_SEND_MODE: True
  FAULT_DETECT_MODE: False
  HOST: '192.168.0.8'
  PORT: 8082
  TIMEOUT: 60
  FAULT_DETECT_MODEL: ''
  THRESHOLD: 500

- NAME: 'CoatingMachine'
  CHANNEL_NAMES: ['coating_vib2', 'coating_vib1']
  DATA_SEND_MODE: True
  FAULT_DETECT_MODE: True
  HOST: '192.168.0.8'
  PORT: 8082
  TIMEOUT: 60
  FAULT_DETECT_MODEL: ''
  THRESHOLD: 500


FILE:
  SAVE_PATH: 'data'
  SEND_PATH:


MODEL:
  SEQ_LEN: 30
  LATENT_DIM: 64
  TEST_SIZE: 0.001
  LEARNING_RATE: 0.001
  EPOCH: 3
  BATCH_SIZE: 5
