CLIENT:
  HOST: '192.168.0.8'
  PORT: 8082
  MACHINE_NAME: 'test'
  TIMEOUT: 10

SENSOR:
  RATE: 30
  READ_TIMEOUT: 10
  DEVICES:
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNEL: 'ai0:1'
    CHANNEL_NAMES: ['vib_ai0', 'vib_ai1']

MACHINE:
  - NAME: 'test1'
    CHANNEL_NAMES: [ ]
    FAULT_DETECT: False
    FAULT_DETECT_MODEL: ''
  - NAME: 'test2'
    CHANNEL_NAMES: [ ]
    FAULT_DETECT: False
    FAULT_DETECT_MODEL: ''

FILE:
  DIRECTORY: 'data'
  EXTERNAL_DIRECTORY: 'data'

MODEL:
  SEQ_LEN: 30
  LATENT_DIM: 64
  TEST_SIZE: 0.001
  LEARNING_RATE: 0.001
  EPOCH: 3
  BATCH_SIZE: 5
