DAQ:
  RATE: 30
  DEVICES:
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNELS: ['ai0']
    CHANNEL_NAMES: ['cDAQ1Mod1_ai0']
#  - NAME: 'temp'
#    TYPE: 'TEMP'
#    CHANNELS: ['ai0']
#    CHANNEL_NAMES: ['m1_temp']


MACHINE:
- NAME: 'VacuumPump1'
  CHANNEL_NAMES: ['cDAQ1Mod1_ai0']
  DATA_SEND_MODE: True
  FAULT_DETECT_MODE: False
  HOST: '192.168.0.8'
  PORT: 8082
  TIMEOUT: 60
  FAULT_DETECT_MODEL: 'lstm_ae.h5'
  THRESHOLD: 500


FILE:
  SAVE_PATH: 'data'
  SEND_PATH:
