CLIENT:
  HOST: '192.168.0.8'
  PORT: 8082
  MACHINE_NAME: 'test'
  TIMEOUT: 10

SENSOR:
  RATE: 30
  READ_TIMEOUT: 10
  DEVICES:
  - NAME: 'vib'
    TYPE: 'VIB'
    CHANNEL: 'ai0'
    CHANNEL_NAMES: ['m1_vib']
  - NAME: 'temp'
    TYPE: 'TEMP'
    CHANNEL: 'ai0'
    CHANNEL_NAMES: ['m2_temp']

FILE:
  DIRECTORY: 'data'
  EXTERNAL_DIRECTORY: 'data'