DATA_PATH: '_data'
TEST_PATH: '_test'
MODEL_OUT: 'out'

MACHINE:
  NAME: 'AROPump'

TRAIN:
- SENSOR_NAME: 'aro_vib1'
  SEQ_LEN: 3
  LATENT_DIM: 64
  LEARNING_RATE: 0.001
  EPOCH: 1
  BATCH_SIZE: 150
  THRESHOLD: 1
- SENSOR_NAME: 'aro_vib2'
  SEQ_LEN: 3
  LATENT_DIM: 64
  LEARNING_RATE: 0.001
  EPOCH: 1
  BATCH_SIZE: 150
  THRESHOLD: 1