CONFIG_PATH = 'resources/DAQSystem.conf'
MODEL_DIR = 'resources/model'
DATA_DIR = 'resources/data'
ICON_IMG = 'resources/img/icon.png'
BTN_CLOSE_NORMAL_IMG = 'resources/img/btn/close_normal.png'
BTN_CLOSE_HOVER_IMG = 'resources/img/btn/close_hover.png'
BTN_FOLDER_ACTIVATED_IMG = 'resources/img/btn/folder_activated.png'
BTN_FOLDER_DEACTIVATED_IMG = 'resources/img/btn/folder_deactivated.png'
